import math
import webbrowser
def error(z, sd, n):
	return round((z * sd) / math.sqrt(n), 4)
zs = dict([(70, 1.04), (75, 1.15), (80, 1.282), (85, 1.44), (90, 1.645), (92, 1.75), (95, 1.96), (96, 2.05), (98, 2.33), (99, 2.576), (99.5, 2.807), (99.9, 3.291)])
option = int(input("Choose 1 for Confidence interval, 2 for margin of error and 3 for both: "))

if option == 1:
	mean = float(input("Mean (\\bar{x}) = "))
	n = int(input("Sample size (n) = "))
	sd = float(input("Standard deviation (s) = "))
	ci = int(input("Confidence interval(in %) = "))
	if n < 30:
		webbrowser.open('https://www.danielsoper.com/statcalc/calculator.aspx?id=10')
		t = float(input("t = "))
		print ("t_{\\alpha/2, n-1} = " + str(t))
		print ("Since we know that")
		print ("Confidence\; interval = \\bar{x} \pm t_{\\alpha/2, n-1}\\frac{s}{\sqrt{n}}")
		E = error(t, sd, n)
		ll = round(mean - E, 4)
		ul = round(mean + E, 4)
		print ("Required confidence interval = (" + str(mean) + "-" + str(t) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}}, "+ str(mean) + "+" + str(t) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}})")
		print ("Required confidence interval = (" + str(mean) + "-" + str(E) + ", "+ str(mean) + "+" + str(E) + ")")
		print ("Required confidence interval = (" + str(ll) + ", " + str(ul) + ")")
	else:
		z = zs.get(ci, 0)
		if z == 0:
			z = float(input("z = "))
		print ("z @ " + str(ci) + "% = " + str(z))
		print ("Since we know that")
		print ("Confidence\; interval = \\bar{x} \pm z\\frac{s}{\sqrt{n}}")
		E = error(z, sd, n)
		ll = round(mean - E, 4)
		ul = round(mean + E, 4)
		print ("Required confidence interval = (" + str(mean) + "-" + str(z) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}}, "+ str(mean) + "+" + str(z) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}})")
		print ("Required confidence interval = (" + str(mean) + "-" + str(E) + ", "+ str(mean) + "+" + str(E) + ")")
		print ("Required confidence interval = (" + str(ll) + ", " + str(ul) + ")")
elif option == 2:
	n = int(input("Sample size (n) = "))
	sd = float(input("Standard deviation (s) = "))
	ci = int(input("Confidence interval(in %) = "))
	if n < 30:
		webbrowser.open('https://www.danielsoper.com/statcalc/calculator.aspx?id=10')
		t = float(input("t = "))
		E = error(t, sd, n)
		print ("\\\\t_{\\alpha/2, n-1} = " + str(t))
		print ("\\\\Since\; we\; know\; that")
		print ("\\\\Margin\; of\; error = t_{\\alpha/2, n-1}\\frac{s}{\sqrt{n}}")
		print ("\\\\Margin\; of\; error = " + str(t) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}}")
		print ("\\\\Margin\;of\;error = " + str(E))
	else:
		z = zs.get(ci, 0)
		if z == 0:
			z = float(input("z = "))
		E = error(z, sd, n)
		print ("z @ " + str(ci) + "% = " + str(z))
		print ("Since we know that")
		print ("\\\\Margin\; of\; error = z\\frac{s}{\sqrt{n}}")
		print ("\\\\Margin\; of\; error = " + str(z) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}}")
		print ("\\\\Margin\;of\;error = " + str(E))
elif option == 3:
	mean = float(input("Mean (\\bar{x}) = "))
	n = int(input("Sample size (n) = "))
	sd = float(input("Standard deviation (s) = "))
	ci = int(input("Confidence interval(in %) = "))
	if n < 30:
		webbrowser.open('https://www.danielsoper.com/statcalc/calculator.aspx?id=10')
		t = float(input("t = "))
		print ("\\\\t_{\\alpha/2, n-1} = " + str(t))
		print ("\\\\Since\; we\; know\; that")
		print ("\\\\Confidence\; interval = \\bar{x} \pm t_{\\alpha/2, n-1}\\frac{s}{\sqrt{n}}")
		print ("\\\\And")
		print ("\\\\Margin\; of\; error = t_{\\alpha/2, n-1}\\frac{s}{\sqrt{n}}")
		E = error(t, sd, n)
		ll = round(mean - E, 4)
		ul = round(mean + E, 4)
		print ("\\\\Margin\; of\; error = " + str(t) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}}")
		print ("\\\\Margin\;of\;error = " + str(E))
		print ("Required confidence interval = (" + str(mean) + "-" + str(t) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}}, "+ str(mean) + "+" + str(t) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}})")
		print ("Required confidence interval = (" + str(mean) + "-" + str(E) + ", "+ str(mean) + "+" + str(E) + ")")
		print ("Required confidence interval = (" + str(ll) + ", " + str(ul) + ")")
	else:
		z = zs.get(ci, 0)
		if z == 0:
			z = float(input("z = "))
		print ("z @ " + str(ci) + "% = " + str(z))
		print ("Since we know that")
		print ("\\\\Confidence\; interval = \\bar{x} \pm z\\frac{s}{\sqrt{n}}")
		print ("\\\\And")
		print ("\\\\Margin\; of\; error(E) = z\\frac{s}{\sqrt{n}}")
		E = error(z, sd, n)
		ll = round(mean - E, 4)
		ul = round(mean + E, 4)
		print ("\\\\Margin\; of\; error = " + str(z) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}}")
		print ("\\\\Margin\;of\;error = " + str(E))
		print ("\\\\Required\; confidence\; interval = (" + str(mean) + "-" + str(z) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}}, "+ str(mean) + "+" + str(z) + "\\frac{" + str(sd) + "}{\sqrt{" + str(n) + "}})")
		print ("Required confidence interval = (" + str(mean) + "-" + str(E) + ", "+ str(mean) + "+" + str(E) + ")")
		print ("Required confidence interval = (" + str(ll) + ", " + str(ul) + ")")
print ("Please hit thumps up if the answer helped you.")